language: python

addons:
  apt:
    packages:
      - minisat

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - tests/run_tests.py
