language: python

addons:
  apt:
    packages:
      - minisat

python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - tests/run_tests.py
